services:
  mysqldb:
    image: mysql:8.0.36
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge